#pragma once

# autogenerated with ./gen_attr_kind.py and includes '/usr/lib/llvm/9/include/'

cimport attr_kind

from enum import IntEnum

class AttrKind(IntEnum):
    Alignment = <int> attr_kind.Alignment
    AllocSize = <int> attr_kind.AllocSize
    AlwaysInline = <int> attr_kind.AlwaysInline
    ArgMemOnly = <int> attr_kind.ArgMemOnly
    Builtin = <int> attr_kind.Builtin
    ByVal = <int> attr_kind.ByVal
    Cold = <int> attr_kind.Cold
    Convergent = <int> attr_kind.Convergent
    Dereferenceable = <int> attr_kind.Dereferenceable
    DereferenceableOrNull = <int> attr_kind.DereferenceableOrNull
    ImmArg = <int> attr_kind.ImmArg
    InAlloca = <int> attr_kind.InAlloca
    InReg = <int> attr_kind.InReg
    InaccessibleMemOnly = <int> attr_kind.InaccessibleMemOnly
    InaccessibleMemOrArgMemOnly = <int> attr_kind.InaccessibleMemOrArgMemOnly
    InlineHint = <int> attr_kind.InlineHint
    JumpTable = <int> attr_kind.JumpTable
    MinSize = <int> attr_kind.MinSize
    Naked = <int> attr_kind.Naked
    Nest = <int> attr_kind.Nest
    NoAlias = <int> attr_kind.NoAlias
    NoBuiltin = <int> attr_kind.NoBuiltin
    NoCapture = <int> attr_kind.NoCapture
    NoCfCheck = <int> attr_kind.NoCfCheck
    NoDuplicate = <int> attr_kind.NoDuplicate
    NoFree = <int> attr_kind.NoFree
    NoImplicitFloat = <int> attr_kind.NoImplicitFloat
    NoInline = <int> attr_kind.NoInline
    NoRecurse = <int> attr_kind.NoRecurse
    NoRedZone = <int> attr_kind.NoRedZone
    NoReturn = <int> attr_kind.NoReturn
    NoSync = <int> attr_kind.NoSync
    NoUnwind = <int> attr_kind.NoUnwind
    NonLazyBind = <int> attr_kind.NonLazyBind
    NonNull = <int> attr_kind.NonNull
    OptForFuzzing = <int> attr_kind.OptForFuzzing
    OptimizeForSize = <int> attr_kind.OptimizeForSize
    OptimizeNone = <int> attr_kind.OptimizeNone
    ReadNone = <int> attr_kind.ReadNone
    ReadOnly = <int> attr_kind.ReadOnly
    Returned = <int> attr_kind.Returned
    ReturnsTwice = <int> attr_kind.ReturnsTwice
    SExt = <int> attr_kind.SExt
    SafeStack = <int> attr_kind.SafeStack
    SanitizeAddress = <int> attr_kind.SanitizeAddress
    SanitizeHWAddress = <int> attr_kind.SanitizeHWAddress
    SanitizeMemTag = <int> attr_kind.SanitizeMemTag
    SanitizeMemory = <int> attr_kind.SanitizeMemory
    SanitizeThread = <int> attr_kind.SanitizeThread
    ShadowCallStack = <int> attr_kind.ShadowCallStack
    Speculatable = <int> attr_kind.Speculatable
    SpeculativeLoadHardening = <int> attr_kind.SpeculativeLoadHardening
    StackAlignment = <int> attr_kind.StackAlignment
    StackProtect = <int> attr_kind.StackProtect
    StackProtectReq = <int> attr_kind.StackProtectReq
    StackProtectStrong = <int> attr_kind.StackProtectStrong
    StrictFP = <int> attr_kind.StrictFP
    StructRet = <int> attr_kind.StructRet
    SwiftError = <int> attr_kind.SwiftError
    SwiftSelf = <int> attr_kind.SwiftSelf
    UWTable = <int> attr_kind.UWTable
    WillReturn = <int> attr_kind.WillReturn
    WriteOnly = <int> attr_kind.WriteOnly
    ZExt = <int> attr_kind.ZExt
